repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use latest tag
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.11.0 # Use latest tag or pinned version
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0 # Use latest tag or pinned version
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=79"]
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0 # Use latest tag or pinned version
    hooks:
    -   id: flake8
        args: [
            "--max-line-length=79",
            "--extend-ignore=E203,E501",  # E203 for black compatibility, E501 as black handles line length
        ]
